# Generated by Django 2.2.16 on 2021-03-29 16:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleThemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема статьи')),
            ],
            options={
                'verbose_name': 'Тема статьи',
                'verbose_name_plural': 'Темы статьи',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(max_length=400, verbose_name='Описание товара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('currency', models.CharField(default='руб', max_length=100, verbose_name='Валюта')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='Количестао товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbot.Categories', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Тесты',
                'verbose_name_plural': 'Тест',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя в телеграмме')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email пользователя')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон пользователя')),
                ('invited', models.BooleanField(default=False, verbose_name='Пользователь был приглашен')),
                ('points', models.BigIntegerField(default=0, verbose_name='Баллы пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminbot.Users')),
                ('referrer_id', models.BigIntegerField(verbose_name='ID пользователя, который его привел')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
        migrations.CreateModel(
            name='TestsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('data', models.TextField(verbose_name='Вопрос:варианты, ответа, через, запятую:ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='adminbot.Tests')),
            ],
            options={
                'verbose_name': 'Данные для теста',
                'verbose_name_plural': 'Данные для теста',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('total', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Общая стоимость')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('shipping_address', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Адрес доставки')),
                ('buyer_phone', models.CharField(max_length=100, null=True, verbose_name='Телефон покупателя')),
                ('buyer_email', models.CharField(max_length=255, null=True, verbose_name='Email покупателя')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('buyer', models.ForeignKey(on_delete=models.SET(0), to='adminbot.Users', verbose_name='Покупатель')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbot.Products', verbose_name='ID Товара')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('image', models.ImageField(blank=True, upload_to='bot/adminbot/media/products/', verbose_name='Изображение товара')),
                ('image_unique_id', models.CharField(blank=True, max_length=255, verbose_name='ID файла')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к фотографии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminbot.Products')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('video', models.FileField(blank=True, upload_to='bot/adminbot/media/products/', verbose_name='Видео для товара')),
                ('video_unique_id', models.CharField(blank=True, max_length=255, verbose_name='ID видеоролика')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к видео')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='adminbot.Products')),
            ],
            options={
                'verbose_name': 'Видео для товара',
                'verbose_name_plural': 'Видео для товаров',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статьи')),
                ('intro', models.TextField(blank=True, max_length=500, verbose_name='Вступление')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('preview', models.ImageField(blank=True, upload_to='bot/adminbot/media/articles/', verbose_name='Превью статьи')),
                ('preview_id', models.TextField(blank=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbot.ArticleThemes', verbose_name='Тема статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
